// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD8_3n79ZyCiKLUZ3sztFhuCxKVwIrhFes',
    appId: '1:566996127994:web:3cf34b55a367598914f943',
    messagingSenderId: '566996127994',
    projectId: 'democracia-digital-7a4b8',
    authDomain: 'democracia-digital-7a4b8.firebaseapp.com',
    storageBucket: 'democracia-digital-7a4b8.appspot.com',
    measurementId: 'G-B5PH9PHXS6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBxHPmnpL-YX1DkZEeQRqM-g1wDleGyRjQ',
    appId: '1:566996127994:android:1b4b59e658fb17f114f943',
    messagingSenderId: '566996127994',
    projectId: 'democracia-digital-7a4b8',
    storageBucket: 'democracia-digital-7a4b8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBssuJx8xBORzSsup9aLCSO3g2hkZMIDFs',
    appId: '1:566996127994:ios:e552cadab4787b6114f943',
    messagingSenderId: '566996127994',
    projectId: 'democracia-digital-7a4b8',
    storageBucket: 'democracia-digital-7a4b8.appspot.com',
    androidClientId: '566996127994-dndf7dcs1e9ff880nm8md9lhrfesu4h5.apps.googleusercontent.com',
    iosClientId: '566996127994-hf0quf7spv4sjscjn6e5es43e9ch8m90.apps.googleusercontent.com',
    iosBundleId: 'com.glucorp.subasta',
  );

}